# Generated by Django 2.0.6 on 2018-07-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0015_auto_20161130_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='max_zoom',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='baselayer',
            name='min_zoom',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='baselayer',
            name='url',
            field=models.CharField(blank=True, help_text='Base layer tiles url. e.g. ', max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='mappreset',
            name='overlay_layers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status__show_to_mapper': 'True'}, to='webmap.OverlayLayer', verbose_name='overlay layers'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='marker',
            field=models.ForeignKey(help_text='Select icon, that will be shown in map', limit_choices_to={'layer__status__show_to_mapper': 'True', 'status__show_to_mapper': 'True'}, on_delete=django.db.models.deletion.PROTECT, related_name='pois', to='webmap.Marker', verbose_name='marker'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='properties',
            field=models.ManyToManyField(blank=True, help_text='POI properties', limit_choices_to={'status__show_to_mapper': 'True'}, to='webmap.Property', verbose_name='properties'),
        ),
    ]
