# Generated by Django 2.0.6 on 2018-07-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0017_auto_20180707_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='default_icon_height',
            field=models.IntegerField(default=20, verbose_name='default icon height'),
        ),
        migrations.AddField(
            model_name='property',
            name='default_icon_width',
            field=models.IntegerField(default=20, verbose_name='default icon width'),
        ),
    ]
