# Generated by Django 2.0.6 on 2018-07-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0018_auto_20180712_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='default_icon_height',
            new_name='default_iconheight',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='default_icon_width',
            new_name='default_iconwidth',
        ),
    ]
