# Generated by Django 2.0.6 on 2018-07-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0019_auto_20180712_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='default_iconheight',
            new_name='default_icon_height',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='default_iconwidth',
            new_name='default_icon_width',
        ),
    ]
