# Generated by Django 2.0.6 on 2018-07-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0020_auto_20180712_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='default_icon_height',
        ),
        migrations.RemoveField(
            model_name='property',
            name='default_icon_width',
        ),
        migrations.AddField(
            model_name='marker',
            name='default_icon_height',
            field=models.IntegerField(default=20, verbose_name='default icon height'),
        ),
        migrations.AddField(
            model_name='marker',
            name='default_icon_width',
            field=models.IntegerField(default=20, verbose_name='default icon width'),
        ),
    ]
