# Generated by Django 2.0.6 on 2018-07-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0021_auto_20180712_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='layers',
            field=models.CharField(blank=True, help_text='ONLY applies to WMS layers', max_length=255, null=True, verbose_name='layers'),
        ),
        migrations.AddField(
            model_name='baselayer',
            name='server_type',
            field=models.CharField(choices=[('tile', 'tile'), ('wms', 'wms')], default='tile', max_length=60, verbose_name='Tile server type'),
        ),
    ]
