# Generated by Django 2.0.6 on 2018-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0022_auto_20180713_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselayer',
            name='opacity',
            field=models.FloatField(default=1),
        ),
    ]
